### ISSUE TITLE
errors on loading the plugin

### ISSUE THREAD

**Issue by Boomer-1** [Seggan/Slimy-Power-Suits#11]
I was watching my server load and saw that slimy power suits threw errors into the console. I've attached the logs for you.

[latest.log](https://github.com/Seggan/Slimy-Power-Suits/files/5817909/latest.log)

mc version 1.16.3
slimefun dev 784
cs core lib dev 92
slimy v 9

**Comment by SpeedRunHunter** [comment]
it's a similar problem that litexpansion itself had; according to busybiscuit, both that, and looks like S-P-S uses the depricated `Category.register()` instead of `Category.register(SlimefunAddon)`; or in this case, i guess since this is an addon of an addon for a plugin, the solution could be a LOT different, but it surely worked for just litexpansion, so... I'm not that good at java coding, so what do i know, right? ¯\_(ツ)_/¯

**Comment by Seggan** [comment]
You are correct. Fix pushing soon.

**Comment by Seggan** [comment]
Fixed
